export { ReactComponent as Chart } from './chart-area-solid.svg'
export { ReactComponent as Cog } from './cog-solid.svg'
export { ReactComponent as User } from './user-circle.svg'
export { ReactComponent as Edit } from './edit.svg'
export { ReactComponent as AngleDoubleLeft } from './angle-double-left-solid.svg'
export { ReactComponent as AngleDoubleRight } from './angle-double-right-solid.svg'
export { ReactComponent as AngleLeft } from './angle-left-solid.svg'
export { ReactComponent as AngleRight } from './angle-right-solid.svg'
export { ReactComponent as Briefcase } from './briefcase-solid.svg'
export { ReactComponent as Plus } from './plus-solid.svg'
export { ReactComponent as Trash } from './trash-alt-solid.svg'
export { ReactComponent as CheckCircle} from './check-circle-solid.svg'
export { ReactComponent as CheckSquare} from './check-square-solid.svg'
export { ReactComponent as UserTie} from './user-tie-solid.svg'
export { ReactComponent as UserSolid} from './users-solid.svg'
export { ReactComponent as Search} from './search-solid.svg'
export { ReactComponent as Calendar} from './calendar-solid.svg'
export { ReactComponent as Comment} from './comment-solid.svg'
export { ReactComponent as Bell} from './bell-solid.svg'
export { ReactComponent as InfoCircle} from './info-circle-solid.svg'
export { ReactComponent as DotCircle} from './info-circle-solid.svg'
export { ReactComponent as Times} from './times-solid.svg'
export { ReactComponent as Question} from './question-circle.svg'
export { ReactComponent as Arrows} from './arrows-alt-solid.svg'
